CREATE DATABASE SERVICES;
USE SERVICES;

CREATE TABLE SALARIE (
    id INT NOT NULL AUTO_INCREMENT,
    nom CHAR(64) NOT NULL,
    commentaire CHAR(255) NOT NULL,
    idPoste INT NOT NULL,
    CONSTRAINT pk_SALARIE PRIMARY KEY (id),
    CONSTRAINT fk_SALARIE_POSTE FOREIGN KEY (idPoste) REFERENCES POSTE(id) ON DELETE CASCADE
);


CREATE TABLE POSTE (
    id INT NOT NULL AUTO_INCREMENT,
    libelle CHAR(128) NOT NULL,
    CONSTRAINT pk_POSTE PRIMARY KEY (id)
);